# Fly.io deployment configuration for chatbot-node
app = "chatbot-node"
primary_region = "sin"  # Singapore

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  LOG_LEVEL = "info"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "15s"
    method = "get"
    path = "/health"

# Memory and CPU
[vm]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

